name: Local CI/CD – Develop

on:
  push:
    branches:
      - develop

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run basic tests
        run: npm test

      - name: Stop old containers
        run: docker compose down
        continue-on-error: true

      - name: Build & run containers
        run: docker compose up -d --build