name: Promote to UAT

on:
  workflow_run:
    workflows: ["CI - Develop"]
    types:
      - completed

jobs:
  promote:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge develop into uat
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git fetch origin
          git checkout uat
          git merge origin/develop --no-edit
          git push origin uat
